### ISSUE TITLE
Processor to inject in Solr/SolrCloud

### ISSUE THREAD

**Issue by mathieu-rossignol** [Hurence/logisland#133]
Solr is also widely used as a powerful search engine. Would be good to also support it for a wider Logisland adoption.

**Comment by waschult** [comment]
I vote for supporting solr:)

**Comment by oalam** [comment]
Yes it's a must have.
Don't you you to implement this feature @waschult ;) ?

**Comment by mathieu-rossignol** [comment]
When implementing this one, be sure to support all features of the ES processor like routing (which as of today is not yet implemented in the ES processor)

**Comment by mathieu-rossignol** [comment]
Closing this old one, as a new one #345 can replace this one
