### ISSUE TITLE
Support for SMTP/Mailer Processor

### ISSUE THREAD

**Issue by mathieu-rossignol** [Hurence/logisland#138]
Even if records considered as alerts/notification can be stored in a backend and handled by a console, I think it would be nice to have a mailer processor that allows to send emails as notification.
For instance, any other processor generating an alert event could post a record to a Kafka 'alert_email' topic on which the MailerProcessor would listen.

---------------------------------------------------------------
Simplest processor configuration and record example:

Mailer Processor configuration properties example:
smtp.server = smtp.mydomain.com
smtp.port = 25
smtp.emails = alerts@mydomain.com

In order to generate a mail sending, an input record for this processor would be required to have the following expected fields (for instance):
record_type = alert
alert_msg = "An attempt to crack password for user 'root' on host 'sensible_host' was detected from ip '172.17.0.5'"

---------------------------------------------------------------
More complex processor configuration and record example:

Mailer Processor configuration properties example:
smtp.server = smtp.mydomain.com
smtp.port = 25
smtp.emails = alerts@mydomain.com, soc@mydomain.com
smtp.emails.cc = cc@mydomain.com
smtp.emails.bcc = bcc@mydomain.com
smtp.emails.allow_overwrite = true (if true, use emails in record specific fields if present)
smtp.conn.timeout = 1s
smtp.conn.retry = 2
smtp.subject.default = "Alert from LogIsland security system"
smtp.security.username = xxx (authentication towards SMTP server)
smtp.security.password = xxx
smtp.security.ssl = true
smtp.security.keystore = /path/to/keystore/for/authentication/against/smtp/server
smtp.security.truststore = /path/to/truststore/for/authentication/of/the/smtp/server
....

In order to generate a mail sending, an input record for this processor would be required to have the following expected fields (for instance):
record_type = alert
alert_emails = special@mydomain.com
alert_subject = "[LogIsland] SSH bruteforce password cracking attempt"
alert_msg = "An attempt to crack password for user 'root' on host 'sensible_host' was detected from ip '172.17.0.5'"

**Comment by mathieu-rossignol** [comment]
Implemented in https://github.com/Hurence/logisland/pull/146

**Comment by oalam** [comment]
shall we close this issue ?

**Comment by mathieu-rossignol** [comment]
Yes, strange it seems you reopened it after I closed it.
