### ISSUE TITLE
Make build work if no profile specified (use the highest hdp one)

### ISSUE THREAD

**Issue by mathieu-rossignol** [Hurence/logisland#210]
mvn -Phdp-2.5 clean package -> ok
mvn -Phdp-2.4 clean package -> ok
mvn clean package -> nok

Although **activeByDefault** is specified in hdp-2.5 profile so that it is the default profile if none specified, this does not seem to work and fails with:

[INFO] Compiling 2 source files to /local/logisland/logisland-framework/logisland-bootstrap/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /local/logisland/logisland-framework/logisland-bootstrap/src/main/java/com/hurence/logisland/runner/SparkJobLauncher.java:[18,38] error: cannot find symbol
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Logisland Project Parent ........................... SUCCESS [  0.350 s]
[INFO] logisland-api ...................................... SUCCESS [  2.598 s]
[INFO] logisland-framework ................................ SUCCESS [  0.003 s]
[INFO] logisland-utils .................................... SUCCESS [  5.612 s]
[INFO] logisland-plugins .................................. SUCCESS [  0.002 s]
[INFO] logisland-mailer-plugin ............................ SUCCESS [  1.613 s]
[INFO] logisland-bro-plugin ............................... SUCCESS [  1.998 s]
[INFO] logisland-scripting-processors-plugin .............. SUCCESS [ 11.563 s]
[INFO] logisland-querymatcher-plugin ...................... SUCCESS [  2.207 s]
[INFO] logisland-outlier-detection-plugin ................. SUCCESS [ 22.895 s]
[INFO] logisland-common-processors-plugin ................. SUCCESS [  4.167 s]
[INFO] logisland-elasticsearch-plugin ..................... SUCCESS [  5.561 s]
[INFO] logisland-sampling-plugin .......................... SUCCESS [  2.343 s]
[INFO] logisland-maven-archetypes ......................... SUCCESS [  0.001 s]
[INFO] logisland-plugin-archetype ......................... SUCCESS [  0.626 s]
[INFO] logisland-resources ................................ SUCCESS [  0.296 s]
[INFO] logisland-bootstrap ................................ FAILURE [  0.598 s]
[INFO] logisland-documentation ............................ SKIPPED
[INFO] logisland-assembly ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Comment by oalam** [comment]
one profile was activated automatically because of jdk 8 : http://jlorenzen.blogspot.fr/2008/12/maven-profiles-something-you-need-to.html

**Comment by mathieu-rossignol** [comment]
Fix failed : mvn clean package (with no profile) does not work

**Comment by oalam** [comment]
I've tested the build with mvn clean install -DskipTests
are you really sure that it doesn't build with the HEAD  master ?
what is the output log ?

**Comment by mathieu-rossignol** [comment]
Ok did not see you already pushed your latest modifs (had modified this bug to keep track).
But now with your latest code (commit 81825a5fc0aadfb0563b0a7ffa9afe04e36482b8):
- mvn clean install -DskipTests
OK and logisland-agent-0.10.0-SNAPSHOT.jar and logisland-spark-engine21-0.10.0-SNAPSHOT.jar shipped in assembly
- mvn -P hdp-2.5  clean install -DskipTests
OK and logisland-agent-0.10.0-SNAPSHOT.jar and logisland-spark-engine21-0.10.0-SNAPSHOT.jar shipped in assembly
- mvn -P hdp-2.4  clean install -DskipTests
NOK: builds but  logisland-spark-engine16-0.10.0-SNAPSHOT.jar shipped in assembly instead of 21 version BUT logisland-agent-0.10.0-SNAPSHOT.jar is also shipped which I think should not be the case right ?
