### ISSUE TITLE
Cannot build with HDP2.4

### ISSUE THREAD

**Issue by jerome73** [Hurence/logisland#230]
# Expected behavior and actual behavior.

When building logisland with:
mvn clean
mvn -Phdp-2.4 install package

This builds a tar.gz: logisland-0.10.0-SNAPSHOT-bin.tar.gz
that embeds libs from HDP2.5 and not 2.4
Ex with scala:
-rw-rw---- 1 jarnou jarnou 5,5M mars  22 12:26 ./scala-library-2.11.7.jar
-rw-rw---- 1 jarnou jarnou 414K mars  22 12:26 ./scala-parser-combinators_2.11-1.0.4.jar
-rw-rw---- 1 jarnou jarnou 4,4M mars  22 12:26 ./scala-reflect-2.11.7.jar

Ex with kafka:
-rw-rw---- 1 jarnou jarnou 5,0M mars  24 12:32 ./kafka_2.11-0.10.0.1.jar
-rw-rw---- 1 jarnou jarnou 729K mars  24 12:32 ./kafka-clients-0.10.0.1.jar

With HDP2.4, we would expect kafka 0.8.2 (and not 0.10.0) as well as scala 2.10.x (and not 2.11)

# Steps to reproduce the problem.
mvn clean
mvn -Phdp-2.4 install package

# Specifications like the version of the project, operating system, or hardware.
Ubuntu 16.04 or macos Sierra

**Comment by oalam** [comment]
now the bug has moved to hdp2.5 profile

 mvn install -DskipTests -Phdp-2.5

the kafka and scala dependencies are not bundled into the final assembly lib jar

**Comment by oalam** [comment]
fixed with new profile activation method : 

**mvn install -DskipTests -Dhdp=2.4**
**mvn install -DskipTests -Dhdp=2.5**
