### ISSUE TITLE
Support Expresion language in YAML configuration

### ISSUE THREAD

**Issue by mariemat** [Hurence/logisland#277]
## Goal
The goal of the feature is to allow configuration attributes from a processor to be computed based on the attributa values contained in the current event.

An example is to be able to access an ES index where the index name is the concatenation of a string litteral with the content of the value of an event attribute.

    processor configuration :
      ..
      ..
      index-name: ${"customer" + id}

## Propopsed implementation
* We allow any of the attributes in the configuration to be written in the expression language.
* The distinction between a literal value and an EL content is done with the marker `${ ... }`.
  When a line starts with `${` and ends with `}`, then the content is assumed to be EL content and will be interpreted, else it will be used as-is
* The implementation will be based on the JSR-223 API to be able to replace easily the EL with another one if the one selected does not fit our needs at a later point.
  It is currently planned to use either MVEL or javascript as the EL (using the Nashorn implementation provided by default by Java 8)
  Other pluggable EL could be Python, Ruby, Groovy, Lua, etc

## Modifications
* The main changes are expected to be located into the call `getPropertyValue` from `StandardProcessorContext`.
If the content of the property is an EL content, then a call to `getPropertyValue(propertyName)` will throw an exception.
To be able to retrieve the value for EL content, the processor will need to be call a new method `getPropertyValue(propertyName, event)`
* The methods `isExpressionLanguageSupported could be removed... (?)

## Improvements
It would be greater to be able to automatically provide the PropertyValue without forcing the caller to provide the event.
However, it will not be possible as long as the processor treat lists of events, end not each event individually.
This could become a later improvement to logIsland.

## FAQ
* Why not reuse the NiFi EL?
  NiFi EL is a custom, proprietary language. this is not well suited for reuse. Moreover the NiFi EL language is not an industry standard, and not widly known.

**Comment by jerome73** [comment]
To me the illustration involving index-name is not appropriate as precisely being able to dynamically compute the index-name based on field contained in user record will force to revisit ALL current ES processors implementation.
