### ISSUE TITLE
Make the Maxmind IpToGeo service use the cache service

### ISSUE THREAD

**Issue by mathieu-rossignol** [Hurence/logisland#340]
The current maxmind IpToGeo service implementation uses maxmind cache implem. But looking at the code (see https://github.com/maxmind/MaxMind-DB-Reader-java/blob/master/src/main/java/com/maxmind/db/CHMCache.java), it seems the cache becomes inoperant when full (the cache has no policy to cleanup some entries when it is full).

So I think we must replace the mamxind cache with the Logisland cache service usage.
See also this PR https://github.com/Hurence/logisland/pull/336

**Comment by jerome73** [comment]
FIxed in PR #344
