### ISSUE TITLE
The IpToGeo processor cannot use Logisland LRU cache service

### ISSUE THREAD

**Issue by jerome73** [Hurence/logisland#343]
# Expected behavior and actual behavior.
As of now the IpToGeo processor does not offer the possibility to use the Logisland LRU cache service.
It would be nice to be able to use the LRU cache service to avoid accessing the Geolite db for each request.

# Steps to reproduce the problem.

# Specifications like the version of the project, operating system, or hardware.

**Comment by mathieu-rossignol** [comment]
This is a duplicate of https://github.com/Hurence/logisland/issues/340
Do not forget to close both please

**Comment by jerome73** [comment]
duplicate of issue #340
