### ISSUE TITLE
Add a SolR service

### ISSUE THREAD

**Issue by oalam** [Hurence/logisland#345]
Same features as elasticsearch service

- make one search-service-api for ES/SOLR
- implementation for SOLR 5.5.5
- implementation for SOLR 6.6.2
- add tests on embedded server

**Comment by mathieu-rossignol** [comment]
Duplicate of https://github.com/Hurence/logisland/issues/345, closing the old one.

**Comment by mathieu-rossignol** [comment]
Support for routing equivalent would be nice. By the way does the ES service support for routing ? If not one should open an issue for tracking. Routing is great to speeding up ES search requests as it co-locate documents with a same id on the same ES node.
