### ISSUE TITLE
Bro Dockerfile update

### ISSUE THREAD

**Issue by TDominiqueWilliams** [Hurence/logisland#393]
During the building of the bro docker build, it reaches an error when attemtping to clone the bro kafka package. The link no longer holds bro packages and it refers to a new link.

I didn't do a pull request but I changed lines 74 and 75 to the following to make it work:
git clone https://github.com/apache/metron-bro-plugin-kafka.git;   \
cd metron-bro-plugin-kafka;   \

**Comment by mathieu-rossignol** [comment]
Thanks for your contribution. Just changed the docker file as you mentioned.
