### ISSUE TITLE
Documentation broken for some processors

### ISSUE THREAD

**Issue by mathieu-rossignol** [Hurence/logisland#418]
Reading the documentation from https://logisland.readthedocs.io/en/latest/index.html.
At least those 3 processors have strange wrong documentation (see screenshot):
- CheckAlerts
- CheckThresholds
- ComputeTags
`
<p>

    Explanation: all loops (for, do-while, while, and if-else, and functions should use braces, because poison_pill() function will be inserted after each open brace “{“, to ensure interruption checking. Otherwise simple code like: <pre>

        while(true) while(true) {
            // do nothing

        }

    </pre> or even: <pre>

        while(true)

    </pre> cause unbreakable loop, which force this sandbox to use {@link Thread#stop()} which make JVM unstable.

</p> <p>
`

**Comment by mathieu-rossignol** [comment]
![image](https://user-images.githubusercontent.com/18575218/47139339-d93a6400-d2bb-11e8-8fee-8d58b58061cd.png)

**Comment by amarziali** [comment]
Due to unescaping of **"** character. 

As well, description of those processors must be written in RST if any formatting must apply. 

Just fixed both issues. Back to you for verification and closure.

Andrea

**Comment by mathieu-rossignol** [comment]
Ok fixed with https://github.com/Hurence/logisland/commit/b5f4d08a4b3b594244e756e4527b9af3336186c5
