### ISSUE TITLE
add Python processor

### ISSUE THREAD

**Issue by oalam** [Hurence/logisland#43]

**Comment by oalam** [comment]
https://wiki.python.org/jython/JythonMonthly/Articles/September2006/1

**Comment by oalam** [comment]
check python API from Google AppEngine

https://cloud.google.com/appengine/docs/python/apis

**Comment by oalam** [comment]
**Example of processor Properties**

    runtime: python27
    api_version: 1
    threadsafe: true

**Pure Python**

All code for the Python runtime environment must be pure Python, and not include any C extensions or other code that must be compiled.

The environment includes the [Python standard library](https://docs.python.org/release/2.7.2/library/). Some modules should be disabled because their core functions are not supported by Logisland, such as networking or writing to the filesystem. In addition, the os module is available, but with unsupported features disabled. An attempt to import an unsupported module or use an unsupported feature will raise an exception.

A few modules from the standard library have been replaced or customized to work with App Engine. These modules vary between the two Python runtimes, as described below.

_Customized libraries in Python 2.7_

In the Python 2.7 runtime, the following modules have been replaced or customized:

- tempfile is disabled, except for TemporaryFile which is aliased to StringIO.
- logging is available and its use is highly encouraged! See Logging.

In addition to the Python standard library and the Logisland libraries, the Python 2.7 runtime includes several third-party libraries.

- [scikit learn](http://scikit-learn.org/stable/)
- [nltk](http://www.nltk.org/)

see also [NaturalLanguageProcessingWithPython](http://victoria.lviv.ua/html/fl5/NaturalLanguageProcessingWithPython.pdf)

**Comment by mathieu-rossignol** [comment]
I think I've found a very promising post regarding how to sandbox python processors in logisland and handle security related issues:
http://alphaloop.blogspot.fr/2014/08/sandboxing-python-scripts-in-java.html

**Comment by oalam** [comment]
I'm agree. we need a combination of a restrictive classloader and a JVM with a very strict SecurityManager specified.
