### ISSUE TITLE
Cassandra sink service should not insert NULL values

### ISSUE THREAD

**Issue by jerome73** [Hurence/logisland#450]
# Expected behavior and actual behavior.
When inserting records to Cassandra, it is expected to avoid to insert NULL values for columns not having values defined.
Why ? bc Cassandra will create a tombstone. Having tombstones may cause some troubles especially when the number is high for a table; possibly preventing Cassandra from being able to serve client requests for that table.

Instead of inserting records with null values, it is recommended either to omit the column name you are not setting when issuing an INSERT or UPDATE statement or use the unset() method.

WARNING: It is possible as long as the column(s) in question is/are not part of the primary key.

Ex: 
```yml
PreparedStatement statement = session.prepare("INSERT INTO mykeyspace.mytable (key, col_2) values (?,?)");
 
BoundStatement bs = statement.bind(1, "test_value_1", "test_value_2");
bs.unset("col_1");
```
# Steps to reproduce the problem.

# Specifications like the version of the project, operating system, or hardware.

**Comment by mathieu-rossignol** [comment]
Fix has been merged in develop: closing
