### ISSUE TITLE
python tests broken

### ISSUE THREAD

**Issue by lhubert** [Hurence/logisland#454]
# Expected behavior and actual behavior.
When building with tests we get the following error
 [ERROR] Failures: 
[ERROR]   GenderTaggerRunPythonTest.testGenderTagger:91 expected output record count was 19 but is currently 0

# Steps to reproduce the problem.
mvn clean package -Pfull

# Specifications like the version of the project, operating system, or hardware.
develop branch

**Comment by mathieu-rossignol** [comment]
The provided command does not fail in python tests as described. Closing.
