### ISSUE TITLE
Change build/assembly mechanism for easy readability and stability

### ISSUE THREAD

**Issue by mathieu-rossignol** [Hurence/logisland#481]
The current way the packaging is done is a combination of assembly pom.xml and assembly descriptor usage. It is hardly understandable what gets really packaged at the end regarding
plugins, their dependencies, core logisland artifacts...

We propose to refactor this this way:
- remove dependencies list in the assembly pom.
- use instead 2 assembly descriptors (xml files): light and full both corresponding to
the 2 profiles
- in each descriptor, explicitly list plugins jars (fatjars) to include, plus needed common

(may be it is possible to use 3 xmls, one for core shared components and one for each profile to list and add in archive the specific plugins)

Caution: The documentation for developing components will have to be updated accordingly.

**Comment by mathieu-rossignol** [comment]
BTW we already fixed a jarhell issue (multiple versions lucene jars included at the top of the lib dir) in this commit : 38e297501b4e824853a6e195be4da75646cee5a1

**Comment by MiniPlayer** [comment]
Ok, I am starting to work on this.
I will try to make all shared library into one fatjar named something like "logisland-1.1.2.jar".
So the lib directory would looks like 

lib/engines
lib/engines/engine1.jar
lib/engines/...
lib/logisland-X.X.X.jar
lib/plugins/plugin1.jar
lib/plugins/...
