### ISSUE TITLE
enable expression language for FilterRecords

### ISSUE THREAD

**Issue by MiniPlayer** [Hurence/logisland#495]
Currently the processor can only filter on a specific field with a specific value. It would be nice to allow user to use a custom method returning a boolean using expression language, for example: 
```
filter_method: ${field1 == value1 || (field2 == value2 && field3.contains("hello"))}
```
Or even maybe several methods as dynamic properties so the name would mean something, for example : 
```
custom_method: ${field1 == value1 || (field2 == value2 && field3.contains("hello"))}
nombre_de_tomate_trop_petit: ${nombre_tomate < 10}
```
Maybe we could add a strategy property to choose a OR or AND logic between all methods : 
```
logic : AND
custom_method: ${field1 == value1 || (field2 == value2 && field3.contains("hello"))}
nombre_de_tomate_trop_petit: ${nombre_tomate < 10}
```

**Comment by lhubert** [comment]
For a first implementation I think a set of filter_method would do
can we have:
filter_method: ${field1 == value1 || (field2 == value2 && field3.contains("hello"))}
filter_method: ${field3.contains("bye")}
and by default it is a OR logic
and can we call it just filter ?

**Comment by MiniPlayer** [comment]
Well I opened this morning the PR #497.
I put by default a AND logic.
And we can have a set of filter_method but the key have to be different each time (by design)
so to do your example you could do :
```
logic: OR
filter_method: ${field1 == value1 || (field2 == value2 && field3.contains("hello"))}
filter_method_2: ${field3.contains("bye")}
```

I could change the default of logic but I am not sure one is really more relevant than another.
