### ISSUE TITLE
add EncodeBase64 Processor

### ISSUE THREAD

**Issue by oalam** [Hurence/logisland#498]
# Expected behavior and actual behavior.
Encodes or decodes content to and from base64

# Steps to reproduce the problem.

# Specifications like the version of the project, operating system, or hardware.

**Comment by amarziali** [comment]
Hey @oalam maybe is too minimalistic but something like this may also work ? ;-)

`
- processor: add_fields
          component: com.hurence.logisland.processor.AddFields
          type: processor
          configuration:
            my_base64_field: ${com.hurence.logisland.util.string.BinaryEncodingUtils.encode(record_value.getBytes())}
`

**Comment by oalam** [comment]
great hack, not so user friendly but a big part of the implementation

**Comment by amarziali** [comment]
True. Feel free to assign to me. I've some spare time this week. I'll be glad to contribute with an easy ticket ;)

**Comment by oalam** [comment]
it's your now ! thanks for your help & welcome back into streaming business :)
