### ISSUE TITLE
Rename Processor.process methods to allow bridging with some scripting languages like python

### ISSUE THREAD

**Issue by mathieu-rossignol** [Hurence/logisland#83]
Putting my Gitter message as Issue description:

Hello, I am currently in the process of writing a bridge processor for python so that we can leverage python libraries in logisland. I am currently facing this problem : when I call the process method of the python processor, there is no way to distinguish which version of the process method this will call : the version with a single record as parameter or the version with a collection of records as parameters. This is because python (and I guess some other scripting languages) has not like java the ability to distinguish methods with the same name (in the same class) according to its parameters type. For workarouding this problem and also in my opinion so that we have something clearer when reading, I propose the following: In the Processor interface, one should rename the 2 process methods like this : version with one record:
Collection<Record> processRecord(ProcessContext context, Record record)
version with a collection of records:
Collection<Record> processRecords(ProcessContext context, Collection<Record> records)
do you agree?

**Comment by mathieu-rossignol** [comment]
We may also simply remove the Processor.process method with one record as parameter, which is in fact not currently called by the framework.

**Comment by oalam** [comment]
I'm ok with that option as the single Record contract is not used yet

**Comment by oalam** [comment]
done in https://github.com/Hurence/logisland/commit/59fc0e058dc8bf347cb4621daf7df02374c2b264
